package hrms.human_resource_system.service;

import hrms.human_resource_system.model.Employee;
import hrms.human_resource_system.model.User;
import hrms.human_resource_system.repository.*;
import org.mindrot.jbcrypt.BCrypt;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.function.Supplier;

@Service
public class UserService {

    private final UserDAO userDAO;
    private final RoleDAO roleDAO;
    private final EmployeeDAO employeeDAO;
    private final NationalityDAO nationalityDAO;
    private final DepartmentDAO departmentDAO;
    private final PositionDAO positionDAO;

    @Autowired
    public UserService(UserDAO userDAO, RoleDAO roleDAO, EmployeeDAO employeeDAO, NationalityDAO nationalityDAO, DepartmentDAO departmentDAO, PositionDAO positionDAO) {
        this.userDAO = userDAO;
        this.roleDAO = roleDAO;
        this.employeeDAO = employeeDAO;
        this.nationalityDAO = nationalityDAO;
        this.departmentDAO = departmentDAO;
        this.positionDAO = positionDAO;
    }

    private <T> T wrap(Supplier<T> action) {
        try {
            return action.get();
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("Unexpected error: " + e.getMessage(), e);
        }
    }

    private void validateUser(User user, int userIdToUpdate) {
        if (user.getUsername() == null || user.getUsername().isBlank()) {
            throw new IllegalArgumentException("Username is required.");
        }

        User existingUser = userDAO.getByUsername(user.getUsername());
        if (existingUser != null && (userIdToUpdate == -1 || existingUser.getId() != userIdToUpdate)) {
            throw new IllegalArgumentException("Username already exists.");
        }

        if (roleDAO.getById(user.getRole().getId()) == null) {
            throw new IllegalArgumentException("Role does not exist.");
        }
    }

    @Transactional
    public User createUser(String username, String hashedPassword, int roleId) {
        return wrap(() -> {
            User newUser = new User();
            newUser.setUsername(username);
            newUser.setPassword(hashedPassword);
            newUser.setRole(roleDAO.getById(roleId));

            validateUser(newUser, -1);
            userDAO.insert(newUser); // sets ID

            String roleName = newUser.getRole().getName();
            List<String> employeeRoles = List.of("Admin", "HR", "Employee");

            if (employeeRoles.contains(roleName)) {
                Employee employee = new Employee();
                long timestamp = System.currentTimeMillis();

                employee.setPIN("PIN-" + timestamp);
                employee.setFirstName(username);
                employee.setLastName("AutoGenerated");
                employee.setBirthDate(LocalDate.of(1990, 1, 1));
                employee.setDateOfHire(LocalDate.now());
                employee.setDateOfDismissal(null);
                employee.setPhoneNumber("000-000-0000");
                employee.setEmail(username + "+" + timestamp + "@autogen.local");
                employee.setAddress("Autogenerated");
                employee.setGender("Other");

                employee.setNationality(nationalityDAO.getAll().get(0));
                employee.setDepartment(departmentDAO.getAll().get(0));
                employee.setPosition(positionDAO.getAll().get(0));

                employee.setEmploymentStatus("Active");
                employee.setEmergencyContactName("N/A");
                employee.setEmergencyContactPhone("N/A");
                employee.setMaritalStatus("Single");
                employee.setEmploymentType("Full-Time");
                employee.setManager(null);
                employee.setTaxId("TAX-" + newUser.getId());
                employee.setBankAccountNumber("HR" + timestamp);

                employee.setUserId(newUser.getId());
                employeeDAO.insert(employee, newUser.getId());

                // Link in User table too
                userDAO.linkEmployee(newUser.getId(), employee.getId());
                newUser.setEmployeeId(employee.getId());
            }

            return newUser;
        });
    }

    public User updateUser(int id, String username, String password, int roleId) {
        return wrap(() -> {
            User existingUser = userDAO.getById(id);
            if (existingUser == null) {
                throw new IllegalArgumentException("User not found.");
            }

            existingUser.setUsername(username);
            existingUser.setPassword(BCrypt.hashpw(password, BCrypt.gensalt())); // Hash password
            existingUser.setRole(roleDAO.getById(roleId));

            validateUser(existingUser, id);
            userDAO.update(id, existingUser);
            return existingUser;
        });
    }

    public List<User> getAllUsers() {
        return wrap(userDAO::getAll);
    }

    public User getUserById(int id) {
        return wrap(() -> userDAO.getById(id));
    }

    @Transactional
    public void deleteUser(int id) {
        wrap(() -> {
            Employee employee = employeeDAO.getByUserId(id);
            if (employee != null) {
                employeeDAO.unlinkUser(employee.getId());      // ✨ THIS FIXES THE FK ERROR
                employeeDAO.delete(employee.getId(), id);      // Soft delete
            }
            userDAO.delete(id);                                 // Hard delete
            return null;
        });
    }
}
